"""Generate a strong random DB key and write scripts-local writ_key.py.

writ_key.py is baked into the exe by PyInstaller (see Writ.spec) and
.gitignore-d so it never lands in git. The SAME key must be exported as
WRIT_DB_KEY when running build_encrypted_db.py.

Usage:
    ./venv/bin/python scripts/generate_key.py [--print-export]
    ./venv/bin/python scripts/generate_key.py --from-env   # CI: reuse WRIT_DB_KEY secret
"""

import argparse
import os
import secrets

OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "writ_key.py"
)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--print-export", action="store_true")
    ap.add_argument(
        "--from-env",
        action="store_true",
        help="use WRIT_DB_KEY from environment instead of generating",
    )
    args = ap.parse_args()
    if args.from_env:
        key = os.environ.get("WRIT_DB_KEY", "")
        if not key:
            raise SystemExit("ERROR: --from-env needs WRIT_DB_KEY in the environment.")
    else:
        key = secrets.token_hex(32)
    with open(OUT, "w") as f:
        f.write("# AUTO-GENERATED by scripts/generate_key.py — DO NOT COMMIT.\n")
        f.write(f'DB_KEY = "{key}"\n')
    os.chmod(OUT, 0o600)
    print(f"Wrote {OUT} (mode 600). Now build the DB with the same key:")
    print(f'  WRIT_DB_KEY="{key}" ./venv/bin/python build_encrypted_db.py')
    if args.print_export:
        print(f'\n export WRIT_DB_KEY="{key}"')


if __name__ == "__main__":
    main()
